// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaQBsy3Li-8TR1q5X9gE8B-3UkO9eOri4',
    appId: '1:962901246025:web:310e9b7f425c3a2c7fff98',
    messagingSenderId: '962901246025',
    projectId: 'fitsmart-a3686',
    authDomain: 'fitsmart-a3686.firebaseapp.com',
    storageBucket: 'fitsmart-a3686.firebasestorage.app',
    measurementId: 'G-W0DRCJVDMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3BghG8IjqvMnfZvvCSjn1nAE3BHBjQ6s',
    appId: '1:962901246025:android:e3278f10fcef00987fff98',
    messagingSenderId: '962901246025',
    projectId: 'fitsmart-a3686',
    storageBucket: 'fitsmart-a3686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABqAmLt7nnim8K9RPkG2cY5t7u53wXNs8',
    appId: '1:962901246025:ios:e881e65d206e27087fff98',
    messagingSenderId: '962901246025',
    projectId: 'fitsmart-a3686',
    storageBucket: 'fitsmart-a3686.firebasestorage.app',
    iosClientId: '962901246025-0cu711lg16hq5esit3tv581fdhtt65vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitsmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABqAmLt7nnim8K9RPkG2cY5t7u53wXNs8',
    appId: '1:962901246025:ios:e881e65d206e27087fff98',
    messagingSenderId: '962901246025',
    projectId: 'fitsmart-a3686',
    storageBucket: 'fitsmart-a3686.firebasestorage.app',
    iosClientId: '962901246025-0cu711lg16hq5esit3tv581fdhtt65vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitsmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaQBsy3Li-8TR1q5X9gE8B-3UkO9eOri4',
    appId: '1:962901246025:web:6968620f871eb9717fff98',
    messagingSenderId: '962901246025',
    projectId: 'fitsmart-a3686',
    authDomain: 'fitsmart-a3686.firebaseapp.com',
    storageBucket: 'fitsmart-a3686.firebasestorage.app',
    measurementId: 'G-S6VZV5SH4Q',
  );
}
